plugins/Admin/config/routes.php
<?php
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::plugin(
    'Admin',
    ['path' => '/admin'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
    }
);

plugins/Admin/src/Model/Table/SchedulesTable.php
<?php
namespace Admin\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Schedules Model
 *
 * @property \Admin\Model\Table\CustomersTable&\Cake\ORM\Association\BelongsTo $Customers
 *
 * @method \Admin\Model\Entity\Schedule get($primaryKey, $options = [])
 * @method \Admin\Model\Entity\Schedule newEntity($data = null, array $options = [])
 * @method \Admin\Model\Entity\Schedule[] newEntities(array $data, array $options = [])
 * @method \Admin\Model\Entity\Schedule|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\Schedule saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\Schedule patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Admin\Model\Entity\Schedule[] patchEntities($entities, array $data, array $options = [])
 * @method \Admin\Model\Entity\Schedule findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class SchedulesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('schedules');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Contacts', [
            'foreignKey' => 'contact_id',
            'joinType' => 'INNER',
            'className' => 'Admin.Contacts',
        ]);

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
            'className' => 'Admin.Users',
        ]);

        $this->belongsTo('Gateways', [
            'foreignKey' => 'gateway_id',
            'className' => 'Admin.Gateways',
        ]);

    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('sms_body')
            ->maxLength('sms_body', 160)
            ->requirePresence('sms_body', 'create')
            ->notEmptyString('sms_body');

        $validator
            ->scalar('status')
            ->notEmptyString('status');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['contact_id'], 'Contacts'));
        return $rules;
    }

}

plugins/Admin/src/Model/Table/UsersTable.php
<?php
namespace Admin\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property &\Cake\ORM\Association\BelongsTo $Groups
 *
 * @method \Admin\Model\Entity\User get($primaryKey, $options = [])
 * @method \Admin\Model\Entity\User newEntity($data = null, array $options = [])
 * @method \Admin\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \Admin\Model\Entity\User|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\User saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Admin\Model\Entity\User[] patchEntities($entities, array $data, array $options = [])
 * @method \Admin\Model\Entity\User findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class UsersTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('users');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Groups', [
            'foreignKey' => 'group_id',
            'joinType' => 'INNER',
            'className' => 'Admin.Groups',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('username')
            ->maxLength('username', 100)
            ->requirePresence('username', 'create')
            ->notEmptyString('username');

        $validator
            ->scalar('password')
            ->maxLength('password', 255)
            ->requirePresence('password', 'create')
            ->notEmptyString('password');

        $validator
            ->boolean('active')
            ->allowEmptyString('active');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['username']));
        $rules->add($rules->existsIn(['group_id'], 'Groups'));

        return $rules;
    }
}

plugins/Admin/src/Template/Element/contacts_history_table.ctp
<div class="filter-container">


</div>

<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <table id="contacts" class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th class="text-right">Date</th>
                    <th class="text-right">Statut</th>
                    <th class="text-right">Numéro</th>
                    <th class="text-right">Envoyé par</th>
                    <th class="text-right">Passerelle</th>
                    <th class="text-right">Message</th>
                    <th class="text-right">Actions</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($data as $d): ?>
                    <tr>
                        <td><?= $d->id ?></td>

                        <td class="text-right">
                            <?= $d->created->i18nFormat('dd/MM/yyyy h:mm:ss') ?>
                        </td>

                        <td class="text-right">
                            <a href="javascript:void(0)">
                                <?php

                                // Refactor into an UI Element
                                $element = '';
                                switch ($d->status) {
                                    case 'pending':
                                        $element = "<span class='badge badge-warning'>En attente</span>";
                                        break;

                                    case 'sent':
                                        $element = "<span class='badge badge-success'>Envoyé</span>";
                                        break;

                                    case 'failed':
                                        $element = "<span class='badge badge-danger'>Echoué</span>";
                                        break;

                                    case 'deleted':
                                        $element = "<span class='badge badge-danger'>Supprimé</span>";
                                        break;

                                }

                                echo $element;

                                ?>
                            </a>
                        </td>

                        <td class="text-right">
                            <?= $d->contact->mobile_phone ?>
                        </td>

                        <td class="text-right">
                            <?= $d->user ? $d->user->username : 'N/D' ?>
                        </td>

                        <td class="text-right">
                            <?=
                                $d->gateway ? $d->gateway->code : 'N/D'
                            ?>
                        </td>

                        <td class="text-right">
                            <?= $this->Text->excerpt($d->sms_body, 'method', 50, '...') ?>


                        <td class="text-right">
                            <?= $this->Html->link(
                                'Supprimer',
                                [
                                    'controller' => 'History', 'action' => 'delete', $d->id
                                ],
                                [
                                    'confirm' => 'êtes-vous sûr de vouloir supprimer le SMS ?',
                                    'class' => "btn btn-danger btn-sm br-round"
                                ]
                            ) ?>
                        </td>

                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>


        </div>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {

        const contactsTable = $('#contacts').DataTable({
            dom: 'Bfrtip',
            searching: true,

            columnDefs: [
                {
                    "targets": [0],
                    "visible": false,
                    "searchable": true
                },
                {
                    "targets": [1],
                    "visible": true,
                    "searchable": true,
                    "orderable": false
                }
            ],

            "pageLength": 100,

            order: [[0, "desc"]],

            language: {
                search: "",
                searchPlaceholder: "Recherche ...",
                processing: "Traitement en cours...",
                lengthMenu: "Afficher _MENU_ &eacute;l&eacute;ments",
                info: "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                infoEmpty: "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                infoFiltered: "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                infoPostFix: "",
                loadingRecords: "Chargement en cours...",
                zeroRecords: "Aucun &eacute;l&eacute;ment &agrave; afficher",
                emptyTable: "Aucune donnée disponible dans le tableau",
                paginate:
                    {
                        next: "Suivant",
                        previous: "Précédent",
                        entries: "Entrées",
                        showing: "Affichage",
                    }
            },

            "footerCallback": function (row, data, start, end, display) {
            }

        });

</script>

<style type="text/css">

    input[type="search"] {
        padding: 8px;
    }

    table.dataTable thead th, table.dataTable thead td {
        padding: 10px 18px;
        border-bottom: none;
    }

    .filter-container {

        display: flex;

    }

    .filter-container > div {
        flex: 1;
        margin: 0;
    }

    .right-content {

        display: flex;
        justify-content: flex-end;

    }

    .right-content div {
        margin-left: 1em;

    }

    .flex-large {
        width: 400px;
    }

    .br-round {
        border-radius: 25px;
    }

</style>

plugins/Admin/src/Template/Element/contacts_table.ctp
<?php

$tagsToHtml = function (string $flatTag) {
    $tags = explode(',', trim($flatTag));
    return array_map(function ($tag) {
        return "<span class='badge'>" . trim($tag) . "</span>";
    }, $tags);
};

//echo (new \Cake\Auth\DefaultPasswordHasher())->hash("utilisateur@proxidesk.fr");
//die;

?>


<div class="row">
    <div class="col-sm-4">
        <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn waves-effect btn-wj waves-light btn-info"><i class="fa fa-search"></i></button>
            </span>
            <input type="text" id="contacts_search" class="form-control" placeholder="Chercher ...">
        </div>
    </div>
    <div class="col-sm-5"></div>
    <div class="col-sm-3">
        <a href="javascript:void(0)" id="send-group-btn"
           class="btn btn-block btn-wj pull-right br-round">Envoyer un message</a>
    </div>
</div>


<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <table id="contacts" class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <td class="text-left sales-order-all">
                        <input type="checkbox" class="contact-select-all"/>
                    </td>
                    <th class="text-right">Nom</th>
                    <th class="text-right">Prénom</th>
                    <th class="text-right">Mobile</th>
                    <th class="text-right">Adresse</th>
                    <th class="text-right">Tags</th>
                    <th class="text-right">ACTIONS</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($data as $d): ?>
                    <tr>
                        <td><?= $d->id ?></td>
                        <td class="text-left  sales-order">
                            <input type="checkbox" class="contact-item" data-id="<?= $d->id ?>"/>
                        </td>
                        <td class="text-right">
                            <a href="javascript:void(0)">
                                <?= $d->first_name ?>
                            </a>
                        </td>

                        <td class="text-right">
                            <a href="javascript:void(0)">
                                <?= $d->last_name ?>
                            </a>
                        </td>

                        <td class="text-right">
                            <a href="javascript:void(0)">
                                <?= $d->mobile_phone ?>
                            </a>
                        </td>

                        <td class="text-right">
                            <a href="javascript:void(0)">
                                <?= $d->address ?>
                            </a>
                        </td>

                        <td class="text-right">
                            <?php foreach ($tagsToHtml($d->tags) as $htmlTag) {
                                echo $htmlTag;
                            } ?>
                        </td>

                        <td class="text-right">

                            <a href="<?= $this->Url->build(['controller' => 'Contacts', 'action' => 'history', $d->id]) ?>"
                               class="btn btn-default btn-sm br-round">Historique</a>

                            <a href="<?= $this->Url->build(['controller' => 'Contacts', 'action' => 'edit', $d->id]) ?>"
                               class="btn btn-default btn-sm br-round">EDITER</a>

                            <?= $this->Html->link(
                                'Supprimer',
                                [
                                    'controller' => 'Contacts', 'action' => 'delete', $d->id
                                ],
                                [
                                    'confirm' => 'êtes-vous sûr de vouloir supprimer le contact',
                                    'class' => "btn btn-danger btn-sm br-round"
                                ]
                            ) ?>

                        </td>

                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>


        </div>
    </div>
</div>


<div id="sms-template-container">
    <div id="sms-template-window">
        <h4>Choix du template SMS</h4>
        <hr/>
        <ul>
            <?php foreach ($templates as $template): ?>
                <li class="t-item" data-id="<?= $template->id ?>">
                    <div class="template-item">
                        <div>
                            <p>
                                <strong><?= $template->name ?></strong><br/>
                                <span>09/02/2021</span>
                            </p>
                            <span class="badge"><?= $template->active ? 'Actif' : 'Inactif' ?></span>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {

        const contactsTable = $('#contacts').DataTable({
            dom: 'Bfrtip',
            searching: true,

            columnDefs: [
                {
                    "targets": [0],
                    "visible": false,
                    "searchable": true
                },
                {
                    "targets": [1],
                    "visible": true,
                    "searchable": true,
                    "orderable": false
                }
            ],

            "pageLength": 100,

            order: [[0, "desc"]],

            language: {
                search: "",
                searchPlaceholder: "Recherche ...",
                processing: "Traitement en cours...",
                lengthMenu: "Afficher _MENU_ &eacute;l&eacute;ments",
                info: "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                infoEmpty: "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                infoFiltered: "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                infoPostFix: "",
                loadingRecords: "Chargement en cours...",
                zeroRecords: "Aucun &eacute;l&eacute;ment &agrave; afficher",
                emptyTable: "Aucune donnée disponible dans le tableau",
                paginate:
                    {
                        next: "Suivant",
                        previous: "Précédent",
                        entries: "Entrées",
                        showing: "Affichage",
                    }
            },

            "footerCallback": function (row, data, start, end, display) {
            }


        });
        const endpoint = "<?= $this->Url->build(['controller' => 'Contacts', 'action' => 'sendmessage']) ?>";

        const showMessageTemplateDialog = () => $('#sms-template-container').show();

        const hideMessageTemplateDialog = () => $('#sms-template-container').hide();

        const selectMessageTemplate = (id) => currentMessageTemplate = id;

        const clearSelectionList = () => {
            selectedContacts = [];
        };

        const toggleContactSelection = () => {
            // Toggle the selection status
            currentGroupSelection = !currentGroupSelection;
            $('.contact-item').prop('checked', currentGroupSelection);

            // Clear the contact selection
            clearSelectionList();

            // Update contact selection
            $('.contact-item').each(function (index) {
                if (currentGroupSelection) {
                    selectedContacts.push($(this).data('id'));
                }
            });
        };

        const unselectAllContacts = () => {
            $('.contact-item').prop('checked', false);
            $('.contact-select-all').prop('checked', false);
            clearSelectionList();
        }

        // Request the api
        const sendMessage = async (ids) => {

            if (currentMessageTemplate === '') {
                showMessageTemplateDialog();
                return false;
            }

            const request = await fetch(endpoint + '?ids=' + contactSelectionFormat(ids) + '&template=' + currentMessageTemplate)
            const result = await request.json();

            const responseMsg = result.results.success ? 'Messages envoyés' : 'Une erreur est survenue';
            alert(responseMsg);
            unselectAllContacts();
            currentMessageTemplate = '';
        }

        let selectedContacts = [];
        let currentGroupSelection = false;
        let currentMessageTemplate = '';

        const contactSelectionFormat = (params) => params.join(',');

        // Hide the default search input
        $('#contacts_filter').hide();

        // Replace the existing search field
        $('#contacts_search').keyup(function () {
            contactsTable.search($(this).val());
            contactsTable.draw();
        });

        // Single message sending btn
        $('.contact-send-msg').on('click', async function () {
            const ids = [];
            ids.push([].push($(this).data('id')));
            await sendMessage(ids);
        });

        // Click sur les lignes
        $('.contact-item').on('click', function () {

            const id = $(this).data('id');

            if (this.checked)
                selectedContacts.push(id);
            else
                selectedContacts = selectedContacts.filter(function (item) {
                    return item !== id;
                })

        });

        // Group selection
        $('.contact-select-all').on('click', () => toggleContactSelection());

        // Send message button action
        $('#send-group-btn').on('click', async function () {

            // Check if the selection is not empty
            if (selectedContacts.length === 0) {
                alert('Selectionnez au minimum un contact');
                return;
            }

            // Request the API
            await sendMessage(selectedContacts);

        });


        // SMS Template selection
        $('.t-item').on('click', async function () {
            selectMessageTemplate($(this).data('id'));
            hideMessageTemplateDialog();
        });

    });

</script>

<style type="text/css">

    input[type="search"] {
        padding: 8px;
    }

    table.dataTable thead th, table.dataTable thead td {
        padding: 10px 18px;
        border-bottom: none;
    }

    .filter-container {

        display: flex;

    }

    .filter-container > div {
        flex: 1;
        margin: 0;
    }

    .right-content {

        display: flex;
        justify-content: flex-end;

    }

    .right-content div {
        margin-left: 1em;

    }

    .flex-large {
        width: 400px;
    }

    .br-round {
        border-radius: 25px;
    }

    .badge {
        margin-left: 5px;
    }

    #sms-template-container {
        display: none;
        background: rgba(0, 0, 0, .5);
        position: fixed;
        z-index: 8000;
        left: 0;
        top: 0;
        bottom: 0;
        right: 0;
    }

    #sms-template-window {
        border-radius: 5px;
        background: white;
        width: 800px;
        height: 500px;
        overflow: scroll;
        overflow-x: hidden;
        padding: 1em;
        position: absolute;
        left: 50%;
        top: 50%;
        margin-left: -400px;
        margin-top: -250px;
    }

    #sms-template-window ul {
        padding: 0;
        margin: 0
    }

    #sms-template-window ul li {
        list-style: none;
        height: 50px;
        margin-bottom: 10px;
        padding: 1em;
        border-radius: 5px;
        cursor: pointer;
        display: block;
        height: auto;
        background: rgba(234, 232, 232, 0.2);
        border: solid 1px #3333;
    }

    #sms-template-window ul li:hover {
        background: #a4cd00;
        color: white;
    }

</style>

plugins/Admin/src/Template/Element/footer.ctp
<footer class="footer text-center">2021 &copy; PROXIDESK</footer>

plugins/Admin/src/Template/Element/left_menu.ctp
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav">
        <div class="sidebar-head">
            <h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span class="hide-menu"></span>
            </h3></div>
        <ul class="nav" id="side-menu">
            <li>
                <a href="<?= $this->Url->build("/admin/dashboard") ?>">
                    <i class="mdi mdi-chart-bar fa-fw"></i><span class="hide-menu">TABLEAU DE BORD</span>
                </a>
            </li>
            <li class="devider"></li>

            <li>
                <a href="<?= $this->Url->build(['controller' => 'Contacts', 'action' => 'index']) ?>">
                    <i class="mdi mdi-contacts"></i><span class="hide-menu"> CONTACTS</span>
                </a>
            </li>

            <li>
                <a href="<?= $this->Url->build(['controller' => 'Templates', 'action' => 'index']) ?>">
                    <i class="mdi mdi-message"></i><span class="hide-menu"> TEMPLATES SMS</span>
                </a>
            </li>

            <li>
                <a href="<?= $this->Url->build(['controller' => 'History', 'action' => 'index']) ?>">
                    <i class="mdi mdi-history"></i><span class="hide-menu"> HISTORIQUE</span>
                </a>
            </li>

            <?php

                if($this->request->session()->read('Auth.Admin.group_id') === 2) { ?>

                    <li>
                        <a href="<?= $this->Url->build(['controller' => 'Users', 'action' => 'index']) ?>">
                            <i class="mdi mdi-account"></i><span class="hide-menu"> UTILISATEURS</span>
                        </a>
                    </li>

                    <li>
                        <a href="<?= $this->Url->build(['controller' => 'Gateways', 'action' => 'index']) ?>">
                            <i class="mdi mdi-settings"></i><span class="hide-menu"> PASSERELLES</span>
                        </a>
                    </li>

                <?php }

            ?>

            <li class="devider"></li>
            <li>
                <a href="<?= $this->Url->build(['plugin' => 'authentication', 'controller' => 'users', 'action' => 'logout']) ?>"><i
                        class="mdi mdi-logout fa-fw"></i><span class="hide-menu">DECONNEXION</span></a></li>
        </ul>
    </div>
</div>

plugins/Admin/src/Template/Element/loading.ctp
<!-- ============================================================== -->
<!-- Preloader -->
<!-- ============================================================== -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
    </svg>
</div>

plugins/Admin/src/Template/Element/users_table.ctp
<div class="filter-container">
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <table id="users" class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th class="text-right">Utilisateur</th>
                    <th class="text-right">Groupe</th>
                    <th class="text-right">Statut</th>
                    <th class="text-right">ACTIONS</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($data as $d): ?>
                    <tr>
                        <td><?= $d->id ?></td>
                        <td class="text-right">
                            <?= $d->username ?>
                        </td>

                        <td class="text-right">
                            <?= $d->group->name ?>
                        </td>

                        <td class="text-right">
                            <span class="badge <?= $d->active ? 'badge-success' : 'badge-danger' ?>">
                                <?= $d->active ? 'Actif' : 'Inactif' ?>
                            </span>
                        </td>

                        <td class="text-right">
                            <a href="<?= $this->Url->build(['controller' => 'Users', 'action' => 'edit', $d->id]) ?>"
                               class="btn btn-default btn-sm br-round">EDITER</a>
                        </td>

                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>


        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {

        const contactsTable = $('#users').DataTable({
            dom: 'Bfrtip',
            searching: true,

            columnDefs: [
                {
                    "targets": [0],
                    "visible": false,
                    "searchable": true
                },
                {
                    "targets": [1],
                    "visible": true,
                    "searchable": true,
                    "orderable": false
                }
            ],

            "pageLength": 100,

            order: [[0, "desc"]],

            language: {
                search: "",
                searchPlaceholder: "Recherche ...",
                processing: "Traitement en cours...",
                lengthMenu: "Afficher _MENU_ &eacute;l&eacute;ments",
                info: "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                infoEmpty: "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                infoFiltered: "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                infoPostFix: "",
                loadingRecords: "Chargement en cours...",
                zeroRecords: "Aucun &eacute;l&eacute;ment &agrave; afficher",
                emptyTable: "Aucune donnée disponible dans le tableau",
                paginate:
                    {
                        next: "Suivant",
                        previous: "Précédent",
                        entries: "Entrées",
                        showing: "Affichage",
                    }
            },

            "footerCallback": function (row, data, start, end, display) {
            }


        });

    });

</script>

<style type="text/css">

    input[type="search"] {
        padding: 8px;
    }

    table.dataTable thead th, table.dataTable thead td {
        padding: 10px 18px;
        border-bottom: none;
    }

    .filter-container {

        display: flex;

    }

    .filter-container > div {
        flex: 1;
        margin: 0;
    }

    .right-content {

        display: flex;
        justify-content: flex-end;

    }

    .right-content div {
        margin-left: 1em;

    }

    .flex-large {
        width: 400px;
    }

    .br-round {
        border-radius: 25px;
    }

</style>