plugins/Admin/config/routes.php
<?php
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::plugin(
    'Admin',
    ['path' => '/admin'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
    }
);

plugins/Admin/src/Model/Entity/Contact.php
<?php
namespace Admin\Model\Entity;

use Cake\ORM\Entity;

/**
 * Contact Entity
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $mobile_phone
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 */
class Contact extends Entity
{
    const mobileClearPatterns = ['(',')','-','_'];

    protected $_accessible = [
        '*' => true,
    ];

//    protected function _setMobile_phone($mobile)
//    {
//        return array_reduce(self::mobileClearPatterns, function($carry, $pattern) {
//            return trim( str_replace($pattern,'',$carry) );
//        },$mobile);
//    }

}

plugins/Admin/src/Model/Table/ContactsTable.php
<?php

namespace Admin\Model\Table;

use Cake\Database\Exception;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Contacts Model
 *
 * @method \Admin\Model\Entity\Contact get($primaryKey, $options = [])
 * @method \Admin\Model\Entity\Contact newEntity($data = null, array $options = [])
 * @method \Admin\Model\Entity\Contact[] newEntities(array $data, array $options = [])
 * @method \Admin\Model\Entity\Contact|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\Contact saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\Contact patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Admin\Model\Entity\Contact[] patchEntities($entities, array $data, array $options = [])
 * @method \Admin\Model\Entity\Contact findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ContactsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->setTable('contacts');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
        $this->addBehavior('Timestamp');
        $this->hasMany('Schedules');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->nonNegativeInteger('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('first_name')
            ->maxLength('first_name', 50)
            ->requirePresence('first_name', 'create')
            ->notEmptyString('first_name');

        $validator
            ->scalar('last_name')
            ->maxLength('last_name', 50)
            ->requirePresence('last_name', 'create')
            ->notEmptyString('last_name');

        $validator
            ->scalar('mobile_phone')
            ->regex('mobile_phone','/^((\+)33|0)[1-9](\d{2}){4}$/','Veuillez saisir un numéro de mobile valide (+33...)')
            ->requirePresence('mobile_phone', 'create')
            ->notEmptyString('mobile_phone');

        return $validator;
    }

    public function buildRules(RulesChecker $rules): RulesChecker
    {
        //$rules->add($rules->isUnique(['mobile_phone'], 'Le numéro doit être unique'));
        return $rules;
    }

    public function import(array $data): bool
    {

        $entities = [];

        foreach ($data as $item){

            $mobilePhone = array_reduce(['(',')','-','_',' '], function ($carry, $pattern) {
                return trim(str_replace($pattern, '', $carry));
            }, $item['mobile_phone']);

            $entities[] = $this->newEntity([
                'first_name' => $item['first_name'],
                'last_name' => $item['last_name'],
                'mobile_phone' => strpos($mobilePhone, "+33") ?:  '+33' . (int)$mobilePhone,
                'tags' => $item['tags'],
                'address' => $item['address'],
            ]);

        }

        // Persist
        try {

            foreach ($entities as $entity){
                $this->save($entity);
            }

            return true;

        } catch (Exception $e) {

            return false;

        }

    }

}

plugins/Admin/src/Model/Table/SchedulesTable.php
<?php
namespace Admin\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Schedules Model
 *
 * @property \Admin\Model\Table\CustomersTable&\Cake\ORM\Association\BelongsTo $Customers
 *
 * @method \Admin\Model\Entity\Schedule get($primaryKey, $options = [])
 * @method \Admin\Model\Entity\Schedule newEntity($data = null, array $options = [])
 * @method \Admin\Model\Entity\Schedule[] newEntities(array $data, array $options = [])
 * @method \Admin\Model\Entity\Schedule|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\Schedule saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\Schedule patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Admin\Model\Entity\Schedule[] patchEntities($entities, array $data, array $options = [])
 * @method \Admin\Model\Entity\Schedule findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class SchedulesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('schedules');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Contacts', [
            'foreignKey' => 'contact_id',
            'joinType' => 'INNER',
            'className' => 'Admin.Contacts',
        ]);

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
            'className' => 'Admin.Users',
        ]);

        $this->belongsTo('Gateways', [
            'foreignKey' => 'gateway_id',
            'className' => 'Admin.Gateways',
        ]);

    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('sms_body')
            ->maxLength('sms_body', 160)
            ->requirePresence('sms_body', 'create')
            ->notEmptyString('sms_body');

        $validator
            ->scalar('status')
            ->notEmptyString('status');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['contact_id'], 'Contacts'));
        return $rules;
    }

}

plugins/Admin/src/Controller/ContactsController.php
<?php

namespace Admin\Controller;

use Admin\Controller\AppController;
use Admin\Form\AccrediterForm;
use Admin\Form\ContactsImportForm;
use Admin\Repositories\ShortMessageRepository;
use Admin\Services\ConfigService;
use Admin\Services\ShortMessageService;
use Admin\UseCase\SendMessage;
use Cake\ORM\TableRegistry;
use mysql_xdevapi\Exception;

class ContactsController extends AppController
{

    public function beforeRender(\Cake\Event\Event $event)
    {
        $this->viewBuilder()->setLayout('Admin.company_edit');
    }

    public function index()
    {
        $contacts = $this->Contacts->find('all')->where(['deleted' => 0]);
        $templates = TableRegistry::getTableLocator()
            ->get('Templates')
            ->find()
            ->where(['deleted' => 0])
            ->orderAsc('sequence');

        $this->set(compact('contacts', 'templates'));
        $this->render();
    }

    public function view($id = null)
    {
        $company = $this->Companies->get($id, [
            'contain' => ['Users', 'Accounts', 'CompanyTypes']
        ]);
        $this->set('company', $company);
    }

    public function add()
    {

        $this->loadComponent('Admin.AccountPasswordHelper');

        $contact = $this->Contacts->newEntity();

        if ($this->request->is('post')) {

            $contact = $this->Contacts->patchEntity($contact, $this->request->getData());

            if ($this->Contacts->save($contact)) {
                $this->Flash->success(strtoupper(__('Le client a été correctement ajouté')));
                return $this->redirect(['action' => 'index']);
            }

            $this->Flash->error(strtoupper(__('Une erreur est survenue lors de lajout du client')));
        }

        $this->set(compact('contact'));
    }

    public function edit($id = null)
    {
        $contact = $this->Contacts->get($id);

        if ($this->request->is(['patch', 'post', 'put'])) {

            $contact = $this->Contacts->patchEntity($contact, $this->request->getData());

            if ($this->Contacts->save($contact)) {

                $this->Flash->success(__('Les nouvelles informations ont été enregistrées'));
                return $this->redirect(['action' => 'index']);

            }

            $this->Flash->error(__(strtoupper("Une erreur est servenue l'ors de la modification")));

        }
        $this->set(compact('contact'));
    }

    public function sendMessage()
    {

        $data = $this->request->getQuery('ids');
        $templateId = $this->request->getQuery('template');
        $loggedUserId = $this->getRequest()->getSession()->read('Auth.Admin.id');
        $messageService = new ShortMessageService($loggedUserId);

        try {

            $result = $messageService->sendBatchMessages(
                explode(',', $data),
                $templateId
            );

            return $this->response
                ->withStatus(200)
                ->withHeader('Content-Type', 'application/json')
                ->withStringBody(
                    json_encode([
                        'results' => [
                            'success' => true,
                            'data' => $result
                        ]
                    ])
                );


        } catch (\Exception $e) {

            return $this->response
                ->withStatus(400)
                ->withHeader('Content-Type', 'application/json')
                ->withStringBody(
                    json_encode([
                        'results' => [
                            'success' => false,
                            'error_message' => $e->getMessage()
                        ]
                    ])
                );

        }

    }

    public function history($id)
    {
        $messages = TableRegistry::getTableLocator()
            ->get('Admin.Schedules')
            ->find('all')
            ->where(['contact_id' => $id])
            ->contain(['Contacts']);

        $this->set('messages', $messages);
    }

    public function import()
    {

        $contactsImportForm = new ContactsImportForm();

        if ($this->request->is('post')) {

            if ($contactsImportForm->execute($this->request->getData())) {

                $model = $this->Contacts;

                if ($model->import($contactsImportForm->getData())) {

                    $this->Flash->success('Contacts importés avec succès');

                } else {

                    $this->Flash->error('Il y a eu un problème lors de l\'importation de la liste de contacts');

                }


            } else {

                $this->Flash->error('Il y a eu un problème lors de l\'importation de la liste de contacts');

            }

            $this->redirect(['action' => 'index']);

        }

        $this->set('contact', $contactsImportForm);

    }

    public function delete($id)
    {
        $this->Contacts->updateAll(['deleted' => 1], ['id' => $id]);
        $this->Flash->success('Contact supprimé');
        $this->redirect(['action' => 'index']);
    }


}

plugins/Admin/src/Template/Contacts/history.ctp
<!-- ============================================================== -->
<!-- Preloader -->
<!-- ============================================================== -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
    </svg>
</div>
<!-- ============================================================== -->
<!-- Wrapper -->
<!-- ============================================================== -->
<div id="wrapper">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <?= $this->Element('Admin.main_menu') ?>
    <!-- End Top Navigation -->
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <?= $this->Element('Admin.left_menu') ?>
    <!-- ============================================================== -->
    <!-- End Left Sidebar -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Page Content -->
    <!-- ============================================================== -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row bg-title">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Historique des messages</h4> </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <!--row -->
            <?= $this->Flash->render() ?>

            <div class="row">

                <div class="col-sm-12">
                    <ol class="breadcrumb" style="background-color: white">
                        <li><a href="#">ACCUEIL</a></li>
                        <li><a href="#">CONTACTS</a></li>
                        <li class="active">Historique</li>
                    </ol>
                </div>

            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <?= $this->Element('Admin.contacts_history_table',['data'=>$messages]) ?>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        <?= $this->element('Admin.footer') ?>
    </div>
    <!-- ============================================================== -->
    <!-- End Page Content -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->

<!-- ============================================================== -->
<!-- All Jquery -->
<!-- ============================================================== -->

<!-- Bootstrap Core JavaScript -->
<?= $this->Html->script('/ample/bootstrap/dist/js/bootstrap.min.js') ?>
<?= $this->Html->script('/ample/plugins/bower_components/datatables/media/js/jquery.dataTables.min',['block'=>'scripts_header']) ?>
<?= $this->Html->script('/ample/plugins/bower_components/bootstrap-select-1.12.4/dist/js/bootstrap-select.min',['block'=>'scripts_header']) ?>


<!-- Menu Plugin JavaScript -->
<?= $this->Html->script('/ample/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js') ?>

<!--slimscroll JavaScript -->
<?= $this->Html->script('/ample/js/jquery.slimscroll.js') ?>

<!--Wave Effects -->
<?= $this->Html->script('/ample/js/waves.js') ?>

<!--Counter js -->
<?= $this->Html->script('/ample/plugins/bower_components/waypoints/lib/jquery.waypoints.js') ?>
<?= $this->Html->script('/ample/plugins/bower_components/counterup/jquery.counterup.min.js') ?>

<!-- Custom Theme JavaScript -->
<?= $this->Html->script('/ample/js/custom.js') ?>
<?= $this->Html->css('/ample/plugins/bower_components/datatables/media/css/jquery.dataTables.min',['block'=>'css_header']) ?>

plugins/Admin/src/Template/Contacts/view.ctp
<!-- ============================================================== -->
<!-- Preloader -->
<!-- ============================================================== -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
    </svg>
</div>
<!-- ============================================================== -->
<!-- Wrapper -->
<!-- ============================================================== -->
<div id="wrapper">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <?= $this->Element('Admin.main_menu') ?>
    <!-- End Top Navigation -->
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <?= $this->Element('Admin.left_menu') ?>
    <!-- ============================================================== -->
    <!-- End Left Sidebar -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Page Content -->
    <!-- ============================================================== -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row bg-title">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">INFORMATIONS SUR L'ENTREPRISE</h4> </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">

                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <!--row -->
            <?= $this->Form->create($company) ?>

            <div class="row">
                <div class="col-sm-10">
                    <ol class="breadcrumb" style="background-color: white">
                        <li><a href="#">ACCUEIL</a></li>
                        <li><a href="#">ENTREPRISES</a></li>
                        <li class="active">DETAILS</li>
                    </ol>
                </div>

                <div class="col-lg-2">
                    <a href="<?= $this->Url->build(['action'=>'index',$company->company_type->name])?>" type="submit" class="btn btn-block btn-default pull-right">RETOUR</a>
                </div>

            </div>


            <?= $this->Flash->render() ?>


            <div class="row">

                <div class="col-sm-6">

                    <div class="white-box">
                        <h3 class="box-title m-b-0">Informations sur l'entreprise</h3>
                        <p class="text-muted m-b-30 font-13"> Les champs récédés d'un * sont obligatoires </p>
                        <div class="row">
                            <div class="col-sm-12 col-xs-12">


                                <div class="row">

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Dénomination</label>
                                            <p><?= h($company->denomination) ?></p>
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>CATEGORIE</label>
                                            <p>
                                                <?= h(strtoupper(

                                                        $company->company_type->name == 'company' ? 'Entreprise' : $company->company_type->name

                                                )) ?>
                                            </p>
                                        </div>
                                    </div>


                                </div>


                                <div class="form-group">
                                    <label>Address</label>
                                    <p><?= $company->address ?></p>
                                </div>


                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>EMAIL</label>
                                            <p><?= h($company->email ? $company->email : 'N.C')  ?></p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>MOBILE</label>
                                            <p><?= h($company->mobile ? $company->mobile : 'N.C') ?></p>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Registre de commerce</label>
                                            <p><?= h($company->rc_n) ?></p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Identifiant Fiscal</label>
                                            <p><?= h($company->iden_fiscal) ?></p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>



                </div>
                <div class="col-sm-6">

                    <div class="white-box">
                        <h3 class="box-title m-b-0">Informations sur le compte</h3>
                        <p class="text-muted m-b-30 font-13"> Les champs récédés d'un * sont obligatoires </p>
                        <div class="row">
                            <div class="col-sm-12 col-xs-12">


                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label>IDENTIFIANT UNIQUE :</label>
                                            <p style="font-size: 16px">
                                                <span class="label label-success"><?= h($company->unique_id) ?></span>
                                            </p>
                                        </div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>CONNEXION</label>
                                            <p><?= h($company->user->active ? 'AUTORISE' : 'NON AUTORISE') ?></p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>PAIEMENT PAR CARTES</label>
                                            <p><?= h($company->account->allow_card_use ? 'AUTORISE' : 'NON AUTORISE') ?></p>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>ID CLIENT</label>
                                            <p><?= h($company->user->identity) ?></p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>CODE PIN</label>
                                            <p>******</p>
                                        </div>
                                    </div>
                                </div>
                                <p class="text-muted m-b-30 font-13"><b>ID Client</b> &amp; <b>Code PIN</b> Servent comme username et password pour la connexion</p>

                                <?php if($company->company_type->name == 'company'): ?>

                                    <!-- informations sur l'entreprise -->
                                    <div>
                                    <hr />

                                    <h3 class="box-title m-b-0">Informations sur l'accréditation</h3>
                                    <p class="text-muted m-b-30 font-13"> Les champs récédés d'un * sont obligatoires </p>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>CREDIT DISPONIBLE</label>
                                                <p><?= h($company->account->credit) ?></p>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>SEUIL DE NOTIFICATION</label>
                                                <p><?= h($company->account->notifications_threshold) ?></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php endif; ?>

                                <!-- SI C UN RESTAURANT OU HOTEL OU SPA -->
                                <?php if( ( $company->company_type->name == 'restaurant' || $company->company_type->name == 'hotel' )): ?>
                                <div>
                                    <hr />
                                    <h3 class="box-title m-b-0">Informations sur les transactions</h3>
                                    <p class="text-muted m-b-30 font-13"> Les champs récédés d'un * sont obligatoires </p>
                                    <div class="row">

                                        <!-- COMMISSION -->
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>COMMISSION (%)</label>
                                                <p><?= h((float)$company->commission) ?></p>
                                            </div>
                                        </div>

                                        <!-- DISCOUNT -->
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>REMISE (%)</label>
                                                <p><?= h((float)$company->discount) ?></p>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <?php endif; ?>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?= $this->Form->end() ?>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        <?= $this->element('Admin.footer') ?>
    </div>
    <!-- ============================================================== -->
    <!-- End Page Content -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->

<!-- ============================================================== -->
<!-- All Jquery -->
<!-- ============================================================== -->

<!-- Bootstrap Core JavaScript -->
<?= $this->Html->script('/ample/bootstrap/dist/js/bootstrap.min.js') ?>

<!-- Menu Plugin JavaScript -->
<?= $this->Html->script('/ample/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js') ?>

<!--slimscroll JavaScript -->
<?= $this->Html->script('/ample/js/jquery.slimscroll.js') ?>

<!--Wave Effects -->
<?= $this->Html->script('/ample/js/waves.js') ?>

<!--Counter js -->
<?= $this->Html->script('/ample/plugins/bower_components/waypoints/lib/jquery.waypoints.js') ?>
<?= $this->Html->script('/ample/plugins/bower_components/counterup/jquery.counterup.min.js') ?>

<!-- Custom Theme JavaScript -->
<?= $this->Html->script('/ample/js/custom.js') ?>

<style type="text/css">

    .error-message {
        color:red;
        padding: 1em;
        padding-left: 0;
    }

    input.form-error {
        border :1px solid red;

    }

</style>